repos:
- repo: local
  hooks:
  - id: pytype
    name: pytype
    entry: pytype
    language: system
    types: [python]
    pass_filenames: false
  - id: update-requirements-txt
    name: update-requirements-txt
    entry: pip
    args: [freeze, \>, requirements.txt]
    pass_filenames: false
    language: system
    types: [python]
    always_run: true
